; ****************************************************************************
; sbrk.s - TRDOS 386 C Standard Library (LIBC 2026)
; ----------------------------------------------------------------------------
; Demand Paging Heap Memory Management for C Compilers (GCC 1.27 / TCC) Porting
; Implementation of: void *sbrk(int increment)
; ****************************************************************************

global _sbrk
extern _end                     ; External symbol generated by GNU Linker (LD)
                                ; representing the absolute end of the program (including BSS)

[BITS 32]

_sbrk:
    ; TRDOS 386 relies on demand paging. sbrk simply shifts the virtual address
    ; tracking boundary. Physical memory allocation occurs dynamically upon the
    ; first memory write/read operation via the kernel page fault handler.

    mov     eax, [.current_brk] ; Load the tracked dynamic memory boundary
    test    eax, eax
    jnz     .do_inc             ; If already initialized, perform layout allocation

    ; First-time initialization: Set the heap start exactly where the Linker 
    ; marked the end of the executable file and its BSS variables.
    mov     eax, _end           ; EAX = Program Size + BSS End Pointer
    mov     [.current_brk], eax ; Initialize tracker storage

.do_inc:
    mov     edx, [esp+4]        ; Fetch argument 1: increment size (bytes)
    
    ; EAX preserves the OLD break address to be returned back to malloc
    add     edx, eax            ; Calculate raw target address boundary
    add     edx, 3              ; Align to 32-bit (DWORD) boundary: Round up
    and     dl, 0xFC            ; Clear lower two bits (~3) to finalize alignment
    
    mov     [.current_brk], edx ; Save the newly aligned dynamic memory limit
    
    ; Return the unmodified previous break address in EAX
    retn

; ----------------------------------------------------------------------------
; Internal Dynamic Storage (Embedded inside text code segment to prevent data section corruption)
; ----------------------------------------------------------------------------
align 4
.current_brk: dd 0              ; Runtime variable holding current heap limit