# Automatically modified for Windows TDM-GCC-32
prefix=C:/TDM-GCC-32/tinycc
bindir=$(prefix)
libdir=$(prefix)/lib
includedir=$(prefix)/include
mandir=$(prefix)/man
MAKE=make
CC=gcc
GCC_MAJOR=3
HOST_CC=gcc
AR=ar
STRIP=strip -s -R .comment -R .note
CFLAGS=-O2 -Wall -DTCC_TARGET_PE -DCONFIG_WIN32 -D_WIN32
LDFLAGS=
LIBSUF=.lib
EXESUF=.exe
ARCH=i386
CONFIG_WIN32=yes
VERSION=0.9.18
SRC_PATH=C:/TDM-GCC-32/tinycc
